config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  
  root 'products#index'

  resources :users do
    member do
      get "logout"
      get "info"
      get "address"
      get "credit"
    end
  end

  resources :products do
    resources :comments, only: :create
    collection do
      get 'get_category_children',defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :credits, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credits#pay'
    end
  end

  resources :purchase, only: :show do
    member do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :searches, only: :index do
    collection do
      get 'detail_search', to: 'searches#detail_search'
    end
  end

  resources :categories, only: :index

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Association
  has_one :address
  has_one :credit

    #出品中
  has_many :selling_products, -> { where("buyer_id is NULL") },class_name: 'Product', foreign_key: 'seller_id'
    #売却済
  has_many :sold_out_products, -> { where("buyer_id is not NULL") },class_name: 'Product', foreign_key: 'seller_id'
  
  has_many :comments
  
  # validation 
  validates :nickname, presence: true, length: {maximum: 15}
  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
    validates :birthday 
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @address = @user.build_address
    render :new_address
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  def cancel
    super
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  def after_sign_up_path_for(resource)
    super(resource)
  end

  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end

  def address_params
    params.require(:address).permit(:delively_last_name, :delively_first_name, :delively_last_name_kana, :delively_first_name_kana, :postcode, :prefecture_id, :city, :block, :building, :phone_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @products = Product.where(seller_id: current_user.id)
  end

  def logout
  end

  def info
  end
  
  def address
  end

  def credit
    # credit = Credit.find_by(user_id: current_user.id)
    credit = Credit.where(user_id: current_user.id).first
    if credit.blank?
      # redirect_to credit_user_path(current_user.id) 
    else
      # Payjp.api_key = Rails.application.credentials[:PAYJP_PRIVATE_KEY]
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
      # Payjp.api_key = 'sk_test_5ba36e12894768954ddeaa4d'
      customer = Payjp::Customer.retrieve(credit.customer_id)
      @default_credit_information = customer.cards.retrieve(credit.card_id)
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user-show__side.html.haml
.user-show__side
  .user-show__side__menu
    %h2.user-show__side__menu__title マイページメニュー
    =link_to "お知らせ", user_path, class: "user-show__side__menu__select"
    =link_to "いいねした商品", user_path, class: "user-show__side__menu__select"
      
  .user-show__side__sell
    %h2.user-show__side__menu__title 商品を出品する
    =link_to "商品を出品する", new_product_path, class: "user-show__side__menu__select"
    =link_to "出品した商品", user_path, class: "user-show__side__menu__select"

  .user-show__side__purchase
    %h2.user-show__side__menu__title 商品を購入する
    =link_to "購入した商品", user_path, class: "user-show__side__menu__select"
    =link_to "最近見た商品", user_path, class: "user-show__side__menu__select"
    =link_to "コメントした商品", user_path, class: "user-show__side__menu__select"
    
  .user-show__side__cog
    %h2.user-show__side__menu__title 設定・その他
    =link_to "会員情報", info_user_path, class: "user-show__side__menu__select"
    =link_to "お届け先情報", address_user_path, class: "user-show__side__menu__select"
    =link_to "お支払情報", credit_user_path, class: "user-show__side__menu__select"
    =link_to "ログアウト", logout_user_path, class: "user-show__side__menu__select"

app/views/users/address.html.haml
= render partial: "products/header"
- breadcrumb :user_address
= breadcrumbs pretext: "",separator: " &rsaquo; "

.user-show
  = render partial: 'user-show__side'

  .user-show__edit
    .user-show__edit__form
      %h2 お届け先情報編集
      .user-show__edit__form__field--name
        %label お届け先お名前(全角)
        %span.user-show__edit__form__field__necessity 必須
        .user-show__edit__form__field--name__area
          %input{type: "text", placeholder: "例) 難波",autofocus: true, class: "user-show__edit__form__field__text-form--name"}
          %input{type: "text", placeholder: "例) 太郎", class: "user-show__edit__form__field__text-form--name"}
      .user-show__edit__form__field--name
        %label お届け先お名前カナ(全角)
        %span.user-show__edit__form__field__necessity 必須
        .user-show__edit__form__field--name__area
          %input{type: "text", placeholder: "例) ナンバ", class: "user-show__edit__form__field__text-form--name"} 
          %input{type: "text", placeholder: "例) タロウ", class: "user-show__edit__form__field__text-form--name"} 
      .user-show__edit__form__field
        %label 郵便番号
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", autocomplete: "postal-code", placeholder: "例) 1234567", class: "user-show__edit__form__field__text-form--name"} 
        %p.user-show__edit__form__field__explanation ※ 半角入力・ハイフン無しでお願いします。
      .user-show__edit__form__field
        %label 都道府県
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", placeholder: "例) 大阪府", class: "user-show__edit__form__field__text-form"}
      .user-show__edit__form__field
        %label 市町村
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", placeholder: "例) 大阪市中央区", class: "user-show__edit__form__field__text-form"}
      .user-show__edit__form__field
        %label 番地
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", placeholder: "例) 難波５丁目１−６０", class: "user-show__edit__form__field__text-form"}
      .user-show__edit__form__field
        %label 建物名
        %span.user-show__edit__form__field__necessity--any 任意
        %br/
        %input{type: "text", placeholder: "例) なんばスカイオ 15階", class: "user-show__edit__form__field__text-form"} 
      .user-show__edit__form__field
        %label 電話番号
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", placeholder: "例) 05031873522", class: "user-show__edit__form__field__text-form"}
        %p.user-show__edit__form__field__explanation ※ 半角入力・ハイフン無しでお願いします。
      .user-show__edit__form__submit
        %input{type: "submit", value: "更新する", class: "user-show__edit__form__submit__btn"}

= render partial: "products/footer"

app/views/users/credit.html.haml
= render partial: "products/header"
- breadcrumb :user_credit
= breadcrumbs pretext: "",separator: " &rsaquo; "

.user-show
  = render partial: 'user-show__side'

  .user-show__credit
    .user-show__credit__menu
      .user-show__credit__menu__list
        %h4 クレジットカード一覧
        - if @default_credit_information.blank?
          =link_to new_credit_path do
            %button.user-show__credit__menu__list__btn クレジットカードを追加する
        - else     
          .user-show__credit__menu__list__card
            = image_tag "credit/logo_visa.gif", class: "user-show__credit__menu__list__card--img"
            %p.user-show__credit__menu__list__card--num
              = "**** **** **** " + @default_credit_information.last4
            %p.user-show__credit__menu__list__card--date
              - exp_month = @default_credit_information.exp_month.to_s
              - exp_year = @default_credit_information.exp_year.to_s.slice(2,3)
              = exp_month + "/" + exp_year
            = form_tag(credit_path(current_user.id), method: :delete, id: 'charge-form',  name: "inputForm", ) do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button.user-show__credit__menu__list__card--delete 削除する 
      %p.user-show__credit__menu__link
        = link_to "お支払方法について", user_path

= render partial: "products/footer"

app/views/users/info.html.haml
= render partial: "products/header"
- breadcrumb :user_info
= breadcrumbs pretext: "",separator: " &rsaquo; "

.user-show
  = render partial: 'user-show__side'

  .user-show__edit
    .user-show__edit__form
      %h2 会員情報編集
      .user-show__edit__form__field
        %label ニックネーム
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text",autofocus: true, placeholder: "例) テック太郎", class: "user-show__edit__form__field__text-form"} 
      .user-show__edit__form__field
        %label メールアドレス
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", autocomplete: "email", placeholder: "PC・携帯どちらでも可", class: "user-show__edit__form__field__text-form"} 
      .user-show__edit__form__field
        %label パスワード
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", autocomplete: "new-password", placeholder: "7文字以上の半角英数字", class: "user-show__edit__form__field__text-form"} 
      .user-show__edit__form__field
        %label パスワード(確認用)
        %span.user-show__edit__form__field__necessity 必須
        %br/
        %input{type: "text", autocomplete: "new-password", placeholder: "もう一度入力してください", class: "user-show__edit__form__field__text-form"} 
        %br/
        %br/
        %b 本人確認
        %p.user-show__edit__form__field__identity 他のお客さまに公開されることはありません。
      .user-show__edit__form__field--name
        %label お名前(全角)
        %span.user-show__edit__form__field__necessity 必須
        .user-show__edit__form__field--name__area
          %input{type: "text", placeholder: "例) 難波", class: "user-show__edit__form__field__text-form--name"}
          %input{type: "text", placeholder: "例) 太郎", class: "user-show__edit__form__field__text-form--name"}
      .user-show__edit__form__field--name
        %label お名前カナ(全角)
        %span.user-show__edit__form__field__necessity 必須
        .user-show__edit__form__field--name__area
          %input{type: "text", placeholder: "例) ナンバ", class: "user-show__edit__form__field__text-form--name"} 
          %input{type: "text", placeholder: "例) タロウ", class: "user-show__edit__form__field__text-form--name"} 
      .user-show__edit__form__field
        %label 生年月日
        %span.user-show__edit__form__field__necessity 必須
        %br/
        .user-show__edit__form__field--birthday
          %input{type: "text", placeholder: "例) 2020", class: "user-show__edit__form__field__text-form--birthday"}
          %span 年
          %input{type: "text", placeholder: "例) 12", class: "user-show__edit__form__field__text-form--birthday"}
          %span 月
          %input{type: "text", placeholder: "例) 12", class: "user-show__edit__form__field__text-form--birthday"}
          %span 日
      .user-show__edit__form__submit
        %input{type: "submit", value: "更新する", class: "user-show__edit__form__submit__btn"}

= render partial: "products/footer"

app/views/users/logout.html.haml
= render partial: "products/header"
- breadcrumb :user_logout
= breadcrumbs pretext: "",separator: " &rsaquo; "

.user-show
  = render partial: 'user-show__side'

  .user-show__logout
    .user-show__logout__area
      = link_to destroy_user_session_path, method: :delete do
        %button.user-show__logout__area__btn ログアウト

= render partial: "products/footer"

app/views/users/show.html.haml
= render partial: "products/header"
- breadcrumb :user_show
= breadcrumbs pretext: "",separator: " &rsaquo; "

.user-show
  = render partial: 'user-show__side'

  .user-show__products
    %h2.user-show__products__title
      出品した商品
    - @products.each do |product|
      = link_to product_path(product.id), class: "user-show__products__link" do
        .user-show__products__link__selling
          .user-show__products__link__selling__img
            = image_tag product.images.first.src.url
          .user-show__products__link__selling__info
            %p.user-show__products__link__selling__info__name
              = product.name
            %span.user-show__products__link__selling__info__heart
            = icon("far", "heart")
            0
            %span.user-show__products__link__selling__info__comment
            = icon("far", "comment")
            = product.comments.count
            - if product.buyer_id.present?
              %span.user-show__products__link__selling__info--sold
                売却済
            - else
              %span.user-show__products__link__selling__info--sale
                出品中
          .user-show__products__link__selling__next
            %span
            = icon("fa", "angle-right")

= render partial: "products/footer"