config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  
  root 'products#index'

  resources :users do
    member do
      get "logout"
      get "info"
      get "address"
      get "credit"
    end
  end

  resources :products do
    resources :comments, only: :create
    collection do
      get 'get_category_children',defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :credits, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credits#pay'
    end
  end

  resources :purchase, only: :show do
    member do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :searches, only: :index do
    collection do
      get 'detail_search', to: 'searches#detail_search'
    end
  end

  resources :categories, only: :index

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController

  require 'payjp'
  before_action :set_product

  def show
    if @product.buyer_id.present?
      redirect_to root_path, alert: "この商品は購入済です"
    elsif @product.seller_id == current_user.id
      redirect_to root_path, alert: "あなたは出品者です"
    else
      credit = Credit.find_by(user_id: current_user.id)
      if credit.present?
        Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
        customer = Payjp::Customer.retrieve(credit.customer_id)
        #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
        @default_credit_information = customer.cards.retrieve(credit.card_id)
      end
    end
  end

  def pay
    if current_user.id != @product.seller.id
      credit = Credit.find_by(user_id: current_user.id)
      Payjp.api_key = Rails.application.credentials.payjp[:PAYJP_SECRET_KEY]
      Payjp::Charge.create(
      amount: (@product.price*1.1).round, #支払金額を入力
      customer: credit.customer_id, #顧客ID
      currency: 'jpy', #日本円
      )
      redirect_to action: 'done' #完了画面に移動
    else
      redirect_to root_path, alert: "自身が出品した商品を購入することはできません"
    end
  end

  def done
    if @product.buyer_id.present?
      redirect_to root_path, alert: "この商品は購入済です"
    else
      @product.update(buyer_id: current_user.id)
    end
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

end

app/views/purchase/done.html.haml
= render partial: "products/header_sub"

.purchase-done
  %h2 購入が完了しました！
  %h2 ありがとうございます！！
  = link_to "ユーザーマイページに戻る", user_path(current_user.id), class: "purchase-done__back"

= render partial: "products/footer_sub"

app/views/purchase/index.html.haml
= render partial: "header_sub"
​
.purchase-main
  .purchase-container
    %h1.purchase__title
      購入内容の確認
    .purchase-product
      .purchase-product__inner
        .purchase-product__box
          = image_tag asset_path("material/icon/icon-01.png"), class:"purchase-product__box__image"
          .purchase-product__box__detail
            %p.purchase-product__box__detail__buy-name
              = @product.name
            %span.purchase-product__box__detail__product-fee
              = (@product.price * 1.1).round
              円
            %span.purchase-product__box__detail__shipping-fee （税込）送料込み
    .purchase-option
      .purchase-option__inner
        .purchase-option__box
          .purchase-option__box__payment
            .purchase-option__box__payment__left
              支払い金額
            .purchase-option__box__payment__right
              = (@product.price * 1.1).round
              円
          .purchase-option__box__credit
            .purchase-option__box__credit__method
              .purchase-option__box__credit__method__left
                お支払い方法
​
              -# 【Todo】【if文】支払い方法登録されていたら表示
              -# = link_to credit_user_path ,class:"purchase-option__box__credit__method__right" do
              -#   変更する
​
            -# 【Todo】支払い方法登録済 > Pay.jpからの情報をもらう      
            -# .purchase-option__box__credit__text
            -#   %p.purchase-option__box__credit__text__type
            -#     クレジットカード 
            -#   %p.purchase-option__box__credit__text__credit-number  
            -#     ********0000
            -#   %p.purchase-option__box__credit__text__use-limit
            -#     有効期限 01/01
​
            -# 支払い方法登録なし
            = link_to new_credit_path, class:"purchase-option__box__credit__btn" do
              支払い方法を入力してください
​
          .purchase-option__box__delivery
            .purchase-option__box__delivery__method
              .purchase-option__box__delivery__method__left
                配送先
​
              -# 配送先登録済  
              = link_to address_user_path ,class:"purchase-option__box__delivery__method__right" do
                変更する
​
            -# 配送先登録済      
            .purchase-option__box__delivery__text
              %p.purchase-option__box__delivery__text__post-number
                = current_user.address.postcode
              %p.purchase-option__box__delivery__text__address 
                = current_user.address.prefecture + current_user.address.city + current_user.address.block
              %p.purchase-option__box__delivery__text__name
                = current_user.address.building
​
            // 配送先登録なし（配送先を登録しないとユーザー登録ができないため不要かも。。。）
            -# = link_to address_user_path, class:"purchase-option__box__delivery__btn" do
            -#   配送先を入力してください
​
          -# 支払い確認の画面に遷移させる
          .purchase-option__box__submit
            = link_to "#", class:"purchase-option__box__submit__btn" do
              購入する
        
= render partial: "footer_sub"

app/views/purchase/show.html.haml
= render partial: "products/header_sub"

.purchase-main
  .purchase-container
    %h1.purchase__title
      購入内容の確認
    .purchase-product
      .purchase-product__inner
        .purchase-product__box
          - @product.images.first(1).each do |image|
            = image_tag image.src.url, class:"purchase-product__box__image"
          .purchase-product__box__detail
            %p.purchase-product__box__detail__buy-name
              = @product.name
            %span.purchase-product__box__detail__product-fee
              = tax_included_price(@product.price)
            %span.purchase-product__box__detail__shipping-fee （税込）送料込み
    .purchase-option
      .purchase-option__inner
        .purchase-option__box
          .purchase-option__box__payment
            .purchase-option__box__payment__left
              支払い金額
            .purchase-option__box__payment__right
              = tax_included_price(@product.price)
          .purchase-option__box__credit
            .purchase-option__box__credit__method
              .purchase-option__box__credit__method__left
                お支払い方法
              -if @default_credit_information.blank?  
              -else
                = link_to credit_user_path(current_user) ,class:"purchase-option__box__credit__method__right" do
                  変更する
          .purchase-option__box__credit__text
            -if @default_credit_information.blank?
              = link_to new_credit_path, class:"purchase-option__box__credit__btn" do
                支払い方法を入力してください
            - else    
              %p.purchase-option__box__credit__text__type
                クレジットカード 
              %p.purchase-option__box__credit__text__credit-number  
                = "**** **** **** " + @default_credit_information.last4
              %p.purchase-option__box__credit__text__use-limit
                有効期限
                - exp_month = @default_credit_information.exp_month.to_s
                - exp_year = @default_credit_information.exp_year.to_s.slice(2,3)
                = exp_month + "/" + exp_year

            

          .purchase-option__box__delivery
            .purchase-option__box__delivery__method
              .purchase-option__box__delivery__method__left
                配送先
              = link_to address_user_path(current_user) ,class:"purchase-option__box__delivery__method__right" do
                変更する
            .purchase-option__box__delivery__text
              %p.purchase-option__box__delivery__text__post-number
                = current_user.address.postcode
              %p.purchase-option__box__delivery__text__address 
                = current_user.address.prefecture.name + current_user.address.city + current_user.address.block
              %p.purchase-option__box__delivery__text__name
                = current_user.address.building
          - if @default_credit_information.blank?
          -else
            .purchase-option__box__submit
              = form_tag(pay_purchase_path, method: :post) do
                %button.purchase-option__box__submit__btn
                  購入する
                    
= render partial: "products/footer_sub"