config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  
  root 'products#index'

  resources :users do
    member do
      get "logout"
      get "info"
      get "address"
      get "credit"
    end
  end

  resources :products do
    resources :comments, only: :create
    collection do
      get 'get_category_children',defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end
  
  resources :credits, only: [:new, :show, :destroy] do
    collection do
      post 'pay', to: 'credits#pay'
    end
  end

  resources :purchase, only: :show do
    member do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

  resources :searches, only: :index do
    collection do
      get 'detail_search', to: 'searches#detail_search'
    end
  end

  resources :categories, only: :index

end

app/models/product.rb
class Product < ApplicationRecord

# Association
  belongs_to :category , optional: true

    #『売り手』情報
  belongs_to :seller, class_name: 'User', optional: true, foreign_key: 'seller_id'
    #『買い手』情報
  belongs_to :buyer, class_name: 'User', optional: true, foreign_key: 'buyer_id'
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :product_status
  belongs_to_active_hash :delively_cost
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delively_days
  belongs_to_active_hash :delively_method

  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy

  # validation
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :name, length: { maximum: 40 }, presence: true
  validates :content, length: { maximum: 1000 }, presence: true
  validates :price, numericality: { :greater_than_or_equal_to => 300, :less_than_or_equal_to => 9999999 }, presence: true
  validates :images, :category_id, :product_status_id, :delively_cost_id, :delively_method_id, :prefecture_id, :delively_days_id, presence: true

  # 前後のレコードを取得するメソッド
  def previous
    Product.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    Product.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end

  def self.search(search)
    return Product.all unless search
    Product.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: [:index, :new, :create,:get_category_children,:get_category_grandchildren]
  before_action :move_to_index, except: [:index, :show]
  before_action :refuse_to_edit, only: :edit
  before_action :set_category, only: [:new, :create, :edit, :update]

  def index
    @products = Product.includes(:images).order('created_at DESC')
  end

  def new
    unless user_signed_in?
      flash[:alert] = "ログインしてください"
      redirect_to root_path
    end
    @product = Product.new
    @product.images.new
    3.times{@product.images.build}
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
  end


  def get_category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: @product.seller_id)
    @image = Image.find_by(product_id: @product.id)
    @images = Image.where(product_id: @product.id)
    @comment = Comment.new
    @comments = @product.comments.includes(:user)
  end

  def edit
    if @product.images.count == 1
      @product.images.new
      2.times{@product.images.build}
    end
    if @product.images.count == 2
      @product.images.new
      1.times{@product.images.build}
    end
    if @product.images.count == 3
      @product.images.new
    end

    grandchild_category = @product.category
    child_category = grandchild_category.parent

    @category_parent_array = ["選択してください"]
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end

    @category_children_array = []
    Category.where(ancestry: child_category.ancestry).each do |children|
      @category_children_array << children
    end

    @category_grandchildren_array = []
    Category.where(ancestry: grandchild_category.ancestry).each do |grandchildren|
      @category_grandchildren_array << grandchildren
    end
  end

  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @product.seller_id && @product.destroy
      redirect_to root_path, alert: "商品を削除しました"
    else
      render :show, alert: "商品削除に失敗しました"
    end
  end
  
  private
  def product_params
    params.require(:product).permit(:name, :content, :bland_name, :price, :prefecture_id, :product_status_id, :delively_days_id , :delively_cost_id, :category_id, :delively_method_id, images_attributes: [:src, :_destroy, :id]).merge(seller_id: current_user.id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def move_to_index
    redirect_to user_session_path unless user_signed_in?
  end

  def refuse_to_edit
    if current_user.id != @product.seller_id
      redirect_to root_path
    end
  end 

  def set_category
    @category_parent_array = Category.where(ancestry: nil).pluck(:name)
  end
  
end

app/helpers/products_helper.rb
module ProductsHelper
  def tax_included_price(price)
    "#{(price*1.1).round.to_s(:delimited)}円"
  end
end

app/views/products/_footer.html.haml
.footer
  .footer__top
    .footer__top__content
      %h4 FURIMAについて
      = link_to "会社概要（運営会社）", "#", class: "footer__top__content__link"
      = link_to "プライバシーポリシー", "#", class: "footer__top__content__link"
      = link_to "FURIMA利用規約", "#", class: "footer__top__content__link"
      = link_to "ポイントに関する特約", "#", class: "footer__top__content__link"
    .footer__top__content
      %h4 FURIMAを見る
      = link_to"カテゴリー一覧", "#", class: "footer__top__content__link"
      = link_to"ブランド一覧", "#", class: "footer__top__content__link"
    .footer__top__content
      %h4 ヘルプ＆ガイド
      = link_to"FURIMAガイド", "#", class: "footer__top__content__link"
      = link_to"FURIMAロゴ利用ガイドライン", "#", class: "footer__top__content__link"
      = link_to"お知らせ", "#", class: "footer__top__content__link"
  .footer__bottom
    .footer__bottom__tilte
      = link_to image_tag(asset_path("material/logo/logo-white.png"),size: "160x80", alt: "サンプル画像"), root_path
    %p © FURIMA

app/views/products/_footer_sub.html.haml
.purchase-footer 
  %ul.purchase-footer__links
    = link_to "#", class:"purchase-footer__atag" do 
      %li.purchase-footer__link
        プライバシーポリシー
    = link_to "#", class:"purchase-footer__atag" do    
      %li.purchase-footer__link
        フリマ利用規約
    = link_to "#", class:"purchase-footer__atag" do    
      %li.purchase-footer__link
        特定商取引に関する表記
  = link_to root_path do
    = image_tag asset_path("material/logo/logo.png"), class:"purchase-footer__logo"
  .purchase-footer__copyright
    ©︎ FURIMA

app/views/products/_header.html.haml
.header
  .header__title
    =link_to root_path do
      = image_tag asset_path("material/logo/logo.png"),class:"header__title-image"
    .header__form
    = form_tag(searches_path,method: :get) do
      = text_field_tag :search, "",placeholder:"何かお探しですか？",class:"form-text"
      .header__title__search
        = submit_tag "", :name => nil ,type: "image", src: "#{asset_path "material/icon/icon-search 1.png"}" ,width: "25",height: "25",class: "header__title__search--image"
  .header__list
    %ul.header__list-left
      %li 
        = link_to "カテゴリー",categories_path,class:"header__list-left-link"
      %li 
        = link_to "ブランド","#",class:"header__list-left-link"
    %ul.header__list-right
      -if user_signed_in?
        %li 
          = link_to "マイページ", user_path(current_user), class:"header__list-right-link"
      -else
        %li 
          = link_to "ログイン",new_user_session_path,class:"header__list-right-link"
        %li 
          = link_to "新規会員登録",new_user_registration_path,class:"header__list-right-link"

app/views/products/_header_sub.html.haml
.purchase-header
  = link_to root_path do
    = image_tag asset_path("material/logo/logo.png"), class:"purchase-header__logo"

app/views/products/edit.html.haml
.product-page
  = render partial: "header_sub"
  .product-ex
    .product-ex__main
      = form_for @product do |f|
        .product-ex__main__input-form
          .product-ex__main__input-form__image
            .product-ex__main__input-form__image__image-title
              %label.product-info 商品画像 
              %span.necessary 必須
            %p.max-uploads
              最大4枚までアップロードできます
            .post__drop__box__container
              .prev-content
              .label-content
              .hidden-content
                .hidden-content-image
                  - @product.images.first(4).each_with_index do |image,i|
                    %img{src:image.src,onerror: "this.onerror = null; this.src=' ';",id:"image-edit#{i}"}
                    %a{id:"hidden-content-edit#{i}"} 編  集
                    :javascript
                      $(function(){
                        $("a").on('click',function(){
                          var obj = document.getElementById('edit');
                          obj.id = "edit0";
                          var img = document.getElementById('edit0');
                          img.style.display = "inline";
                            edit0.addEventListener('change', function(e){
                              var file = e.target.files[0];
                              var fileReader = new FileReader();
                            fileReader.onload = function() {
                              var dataUri = this.result;
                              var img = document.getElementById('image-edit0');
                              img.src = dataUri;
                            }
                              fileReader.readAsDataURL(file);
                            });
                          });
                        $("a").on('click',function(){
                          var obj = document.getElementById('edit');
                          obj.id = "edit1";
                          var img = document.getElementById('edit1');
                          img.style.display = "block";
                            edit1.addEventListener('change', function(e){
                              var file = e.target.files[0];
                              var fileReader = new FileReader();
                              fileReader.onload = function() {
                                var dataUri = this.result;
                                var img = document.getElementById('image-edit1');
                                img.src = dataUri;
                            }
                              fileReader.readAsDataURL(file);
                              });
                              });
                          $("a").on('click',function(){
                          var obj = document.getElementById('edit');
                          obj.id = "edit2";
                          var img = document.getElementById('edit2');
                          img.style.display = "block";
                            edit2.addEventListener('change', function(e){
                              var file = e.target.files[0];
                              var fileReader = new FileReader();
                              fileReader.onload = function() {
                                var dataUri = this.result;
                                var img = document.getElementById('image-edit2');
                                img.src = dataUri;
                            }
                              fileReader.readAsDataURL(file);
                              });
                              });
                          $("a").on('click',function(){
                            var obj = document.getElementById('edit');
                            obj.id = "edit3";
                            var img = document.getElementById('edit3');
                            img.style.display = "block";
                              edit3.addEventListener('change', function(e){
                                var file = e.target.files[0];
                                var fileReader = new FileReader();
                                fileReader.onload = function() {
                                  var dataUri = this.result;
                                  var img = document.getElementById('image-edit3');
                                  img.src = dataUri;
                                }
                                fileReader.readAsDataURL(file);
                              });
                            });
                          });
                = f.fields_for :images do |i|
                  =i.file_field :src,id:"edit"
        %hr.underline
        .product-description
          .product-description__form
            .product-description__form__name-form
              .product-description__form__name-form__name
                %label.product-info 商品名
                %span.necessary 必須
              .input-form
                = f.text_field :name, class: "product-info", placeholder: "40文字まで", type: "text", maxlength: "40", required: "" 
            .description-form
              .description-form__name
                %label.product-info 商品の説明
                %span.necessary 必須
              = f.text_area :content, class: "product-info", rows: "7", maxlength: "1000", required: "", placeholder: "商品の説明（必須 1,000文字以内）\n（色、素材、重さ、定価、注意点など）\n\n例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" 
              .counter 0/1000
        %hr.underline
        .product-detail 
          .product-detail__form
            %p.title-name 商品の詳細
            .category-form
              .category-form__name
                %label.product-info カテゴリー
                %span.necessary 必須
              .select-form
                .listing-product-detail__category
                  .listing-select-wrapper
                    .listing-select-wrapper__box
                    .select-area
                      = f.select :category_id, @category_parent_array, {selected:@product.category.parent.parent.name}, { class: 'product-info',id: 'parent_category' } 
                    .select-area#children_wrapper
                      = f.select :category_id, options_for_select(@category_children_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @product.category.parent.id}),{}, {id:'child_category'}
                    .select-area#grandchildren_wrapper
                      = f.select :category_id, options_for_select(@category_grandchildren_array.map{|b| [b.name, b.id, {data:{category: b.id}}]}, {prompt: "指定なし", selected: @product.category.id}),{}, {id:'grandchild_category'}

            -# jsで実装したときに使うためコメントアウトしてます
            -# .size-form
            -#   .size-form__name
            -#     %label.product-info サイズ
            -#     %span.necessary 必須
              -# .select-form
              -#   .select-area
              -#     = f.collection_select :status_id, Status.all, :id, :name ,class: "product-info", placeholder: "選択して下さい", type: "text", maxlength: "40", required: "" 
            .brand-form
              .brand-form__name
                %label.product-info ブランド
                %span.optional 任意
            .select-form
              .select-area
                = f.text_field :bland_name, class: "product-info", placeholder: "例) シャネル", type: "text", maxlength: "40" 
            .status-form
              .status-form__name
                %label.product-info 商品の状態
                %span.necessary 必須
            .select-form
              .select-area
                = f.collection_select :product_status_id, ProductStatus.all, :id, :name, class: 'product-info', required: ""
        %hr.underline
        .about-delivery
          .about-delivery__form
            .title
              %p.title-name
                配送について
            .cost-form
              .cost-form__name
                %label.product-info 配送料の負担
                %span.necessary 必須
            .select-form
              .select-area
                = f.collection_select :delively_cost_id, DelivelyCost.all, :id, :name, class: 'product-info', required: ""
            .method-form
              .method-form__name
                %label.product-info 配送の方法
                %span.necessary 必須
            .select-form
              .select-area
                = f.collection_select :delively_method_id, DelivelyMethod.all, :id, :name, class: 'product-info', required: ""
            .area-form
              .area-form__name
                %label.product-info 発送元の地域
                %span.necessary 必須
            .select-form
              .select-area
                = f.collection_select :prefecture_id, Prefecture.all, :id, :name, class: 'product-info', required: ""
            .days-form
              .days-form__name
                %label.product-info 発送までの日数
                %span.necessary 必須
            .select-form
              .select-area 
                = f.collection_select :delively_days_id, DelivelyDays.all, :id, :name, class: 'product-info', required: ""
        %hr.underline
        .price
          .price__form
            .price__form__title
              %p.title-name
                価格（¥300〜9,999,999）
            .price-form
              .price-name-box
                .price-name
                  %label.product-info 販売価格
                  %span.necessary 必須
                %span.yen
                  %i.fas.fa-yen-sign
                .yen-form
                  .yen-form__box 
                    = f.number_field :price, class:"yen", placeholder: "0", type: "number", autocomplete: "off", min: "300", max: "9999999", required: "" 
              .fee-form
                .name 販売手数料(10%)
              %hr.underline
              .return-form
                .name 販売利益
        .btn-form
          = f.submit "変更する", class: "product-btn"
          %a.back
            もどる 
        .attention 
          禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして 加盟店規約 に同意したことになります。
  = render partial: "footer_sub"

app/views/products/index.html.haml
%main
  = render partial: "products/header"

  .headline
    =image_tag asset_path("material/pict/bg-mainVisual-pict_pc.jpg")
    .headline__text  
      %h2 人生を変えるフリマアプリ  
      %p.headline__text-letter
        FURIMAはだれでも簡単に出品・購入できる
        %br フリマアプリです
      .headline__text-link
        %P.headline__text-link-app
          =link_to image_tag("https://linkmaker.itunes.apple.com/assets/shared/badges/ja-jp/appstore-lrg.svg",size: '190x60'),"#"
        %p.headline__text-link-google
          =link_to image_tag("https://play.google.com/intl/ja/badges/static/images/badges/ja_badge_web_generic.png"),"#"

  .reason
    .reason__title
      %h2 FURIMAが選ばれる3つの理由
    .reason__text
      %ul
        %li.reason__text-number 1
        %li=image_tag asset_path("material/pict/pict-reason-01.jpg"),size:'320x480'
        %li
          %h3 
            %span 3分
            ですぐ出品
        %li
          %p 
            スマホで入力するだけで簡単に出品で
            %br きる！
      %ul
        %li.reason__text-number 2
        %li=image_tag asset_path("material/pict/pict-reason-02.jpg"),size:'320x480' 
        %li
          %h3 
            %span シンプル
            で使いやすい
        %li
          %p
            めんどくさい入力は必要なく、検索も
            %br 購入もスムーズ！
      %ul
        %li.reason__text-number 3
        %li=image_tag asset_path("material/pict/pict-reason-03.jpg"),size:'320x480' 
        %li.reason__text-list
          %h3 手数料 
          %span 業界最安
        %li.reason__text-letter
          最大3%でお得に出品&購入！

  .grade
    .grade__image
    .grade__text
      %h2 会員数日本一位
      %p
        %br FURIMAは、フリマアプリで最も人気。
        %br 出品・購入回数も業界最多です！
        %br ほしかったあの商品に出会えるかもしれません。
      .grade__text-link
        %P.grade__text-link-app
          =link_to image_tag("https://linkmaker.itunes.apple.com/assets/shared/badges/ja-jp/appstore-lrg.svg",size: '190x60'),"#"
        %P.grade__text-link-google
          =link_to image_tag("https://play.google.com/intl/ja/badges/static/images/badges/ja_badge_web_generic.png"),"#"


  .feature
    .feature__title
      %h2 FURIMAの特徴
    .feature__text
      %ul
        %li=image_tag asset_path("material/icon/icon-01.png"),size:'219x338'
        %li
          %h3 簡単に売り買いできる
          %p 
            スマホひとつで、いつでもどこでも簡単
            %br に出品・購入が可能！
      %ul
        %li=image_tag asset_path("material/icon/icon-03.png"),size:'219x338'
        %li
          %h3 売上金は即日振り込みに対応
          %p 
            午前9時までに振込を依頼いただけれ
            %br ば、翌日に指定の口座に入金いたします！
      %ul
        %li=image_tag asset_path("material/icon/icon-04.png"),size:'219x338'
        %li
          %h3 様々な支払いに対応
          %p 
            お支払いは、クレジットカードだけでな
            %br く、ポイントや売上金など多彩な方法が
            %wbr あります。

  .category
    .category__title
      %h2 ピックアップカテゴリー
      %h3 新規投稿商品
    .category__text
      - @products.first(3).each do |product|
        = link_to product_path(product.id) do
          - if product.buyer_id.present? 
            .category__text__sold 
              %p SOLD
          .category__text__space
            = image_tag product.images.first.src.url,class:"category__text__space__image"
            .category__text__space__name
              %p= product.name
            .category__text__space__price
              %p
                = tax_included_price(product.price)
            .category__text__space__tax
              %p (税込)
    .category__title
      %h2 ピックアップブランド
      %h3 アーカイバ
    .category__text
      - @products.first(3).each do |product|
        = link_to product_path(product.id) do
          - if product.buyer_id.present? 
            .category__text__sold 
              %p SOLD
          .category__text__space
            = image_tag product.images.first.src.url,class:"category__text__space__image"
            .category__text__space__name
              %p= product.name
            .category__text__space__price
              %p
                = tax_included_price(product.price)
            .category__text__space__tax
              %p (税込)

  .publicity
    .publicity__image
    .publicity__text
      %h2 だれでもかんたん、人生を変えるフリマアプリ
      %p 今すぐ無料ダウンロード！
      .publicity__text-link
        %P.publicity__text-link-app
          =link_to image_tag("https://linkmaker.itunes.apple.com/assets/shared/badges/ja-jp/appstore-lrg.svg",size: '190x60'),"#"
        %P.publicity__text-link-google
          =link_to image_tag("https://play.google.com/intl/ja/badges/static/images/badges/ja_badge_web_generic.png"),"#"

= render partial: "products/footer"

.icon
  = link_to new_product_path, class: "icon__link" do
    .icon__link__title
      出品する
    .icon__link__image
      = image_tag asset_path("material/icon/icon_camera.png"),size: "54x54", alt: "サンプル画像"

app/views/products/show.html.haml
= render partial: "products/header"

.product-breadcrumb
  %ul.product-breadcrumb__list
    %li.product-breadcrumb__list__item
      = link_to "FURIMA", root_path, class: "product-breadcrumb__list__item__link"
    %li.product-breadcrumb__list__item
      %span &rsaquo;
    %li.product-breadcrumb__list__item
      = link_to categories_path(anchor: "#{@product.category.parent.parent.name}"), class: "product-breadcrumb__list__item__link" do
        = @product.category.parent.parent.name
    %li.product-breadcrumb__list__item
      %span &rsaquo;
    %li.product-breadcrumb__list__item
      = link_to categories_path(anchor: "#{@product.category.parent.parent.name}"), class: "product-breadcrumb__list__item__link" do
        = @product.category.parent.name
    %li.product-breadcrumb__list__item
      %span &rsaquo;
    %li.product-breadcrumb__list__item
      = link_to categories_path(anchor: "#{@product.category.parent.parent.name}"), class: "product-breadcrumb__list__item__link" do
        = @product.category.name
    %li.product-breadcrumb__list__item
      %span &rsaquo;
    %li.product-breadcrumb__list--this
      = @product.name

.product-show
  .product-show__content
    %h2.product-show__content__title
      = @product.name
    .product-show__content__image
      - if @product.buyer_id == nil
        = image_tag @image.src.url, class: "product-show__content__image__main"
      - else
        %div.product-show__content__image__sold
          = image_tag @image.src.url, class: "product-show__content__image__sold__product"
          .product-show__content__image__sold__text SOLD

      %ul.product-show__content__image__list
        - @images.each do |image|
          %li
            = image_tag image.src.url, class: "product-show__content__image__list__content"

    .product-show__content__price
      %h3.product-show__content__price__title
        = tax_included_price(@product.price)
      %p.product-show__content__price__tax (税込)

    - if user_signed_in? && current_user.id != @product.seller_id
      - if @product.buyer_id == nil
        = link_to purchase_path(@product.id), class: "product-show__content__purchace" do
          %button 購入画面に進む
      - else
        .product-show__content__soldout
          売り切れました

    .product-show__content__explanation
      %p
        = simple_format(@product.content)

    .product-show__content__info
      %table.product-show__content__info__table
        %tbody
          %tr
            %th.product-show__content__info__table--head
              出品者
            %td.product-show__content__info__table--data
              = @user.nickname
          %tr
            %th.product-show__content__info__table--head
              カテゴリー
            %td.product-show__content__info__table--data
              = link_to categories_path(anchor: "#{@product.category.parent.parent.name}"), class: "product-show__content__info__table__category" do
                = @product.category.parent.parent.name
                %br
                = @product.category.parent.name
                %br
                = @product.category.name
          %tr
            %th.product-show__content__info__table--head
              ブランド
            %td.product-show__content__info__table--data
              = @product.bland_name
          %tr
            %th.product-show__content__info__table--head
              商品のサイズ
            %td.product-show__content__info__table--data
          %tr
            %th.product-show__content__info__table--head
              商品の状態
            %td.product-show__content__info__table--data
              = @product.product_status.name
          %tr
            %th.product-show__content__info__table--head
              配送料の負担
            %td.product-show__content__info__table--data
              = @product.delively_cost.name
          %tr
            %th.product-show__content__info__table--head
              発送元の地域
            %td.product-show__content__info__table--data
              = @product.prefecture.name
          %tr
            %th.product-show__content__info__table--head
              発送日の目安
            %td.product-show__content__info__table--data
              = @product.delively_days.name

    %ul.product-show__content__option
      = link_to product_path, class: "product-show__content__option__like" do
        %li.product-show__content__option__like__count
          お気に入り 0
      = link_to product_path, class: "product-show__content__option__report" do
        %li.product-show__content__option__report__link
          不適切な商品の通報

  - if user_signed_in? && current_user.id == @product.seller_id
    .product-show__user-info
      = link_to edit_product_path, class: "product-show__user-info--edit" do
        %button 商品の編集
      %p.product-show__user-info--or or
      = link_to product_path, class: "product-show__user-info--delete", method: :delete, data: { confirm: "本当に削除しますか？" } do
        %button 商品の削除
      
  .product-show__comment
    .product-show__comment__messages
      %ul
        %li.product-show__comment__messages__text
          < コメント一覧 >
        - @comments.each do |comment|
          %li.product-show__comment__messages__text
            %span
              = comment.user.nickname
            ：
            %span
              = comment.text

    -if current_user
      = form_with(model: [@product, @comment], local: true, class: "product-show__comment__form") do |f|
        = f.text_area :text, rows: "3", placeholder: "コメントする", class: "product-show__comment__form__input"
        %p.product-show__comment__form__caution 
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
        - if @product.buyer_id == nil
          = f.submit "コメントする", class: "product-show__comment__form__btn"
        - else
          .product-show__comment__form__sold-btn
            売り切れのためコメントできません

  %ul.product-show__links.product-show__links__clearfix
    - if @product.previous.present?
      %li
        = link_to "前の商品", product_path(@product.previous), class: "product-show__links__prev"
    - if @product.next.present?
      %li
        = link_to "後ろの商品", product_path(@product.next), class: "product-show__links__next"

  %div
    = link_to categories_path(anchor: "#{@product.category.parent.parent.name}"), class: "product-show__more-items" do
      = "#{@product.category.parent.parent.name}をもっと見る"

= render partial: "products/footer"